sudo: required
services:
  - docker
before_install:
  - docker build -t jassikhehra/multi-react -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jassikhehra/multi-react npm test -- --coverage
after_success:
  - docker build -t jassikhehra/multi-client ./client
  - docker build -t jassikhehra/multi-nginx ./nginx
  - docker build -t jassikhehra/multi-server ./server
  - docker build -t jassikhehra/multi-worker ./worker
  - echo "$DOCKER_PASS" |docker login -u "$DOCKER_ID" --password=stdin
  - docker push jassikhehra/multi-client
  - docker push jassikhehra/multi-nginx
  - docker push jassikhehra/multi-server
  - docker push jassikhehra/multi-worker
  