sudo: required
services:
  - docker
before_install:
  - docker build -t jassiv/multi-react -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jassiv/multi-react npm test -- --coverage

after_success:
  - docker build -t jassiv/multi-client ./client
  - docker build -t jassiv/multi-nginx ./nginx
  - docker build -t jassiv/multi-server ./server
  - docker build -t jassiv/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_USER" --password-stdin
  - docker push jassiv/multi-client
  - docker push jassiv/multi-nginx
  - docker push jassiv/multi-server
  - docker push jassiv/multi-worker
